### ISSUE TITLE
HR should be able to see a list of employees

### ISSUE THREAD

**Issue by stevebrownlee** [ill-fated-ducks/workforce-management#1]
**Given** an HR employee wants to view employees
**When** the employee clicks on the Employees item in the navigation bar
**Then** all current employees should be listed with the following information

1. First name and last name
1. Department

**Comment by mitchellblom** [comment]
Reopening. Looks like Start Date and Supervisor are still on the view.

**Comment by mitchellblom** [comment]
View confirmed correct on master branch.
